project:
  type: website

website:
  title: "Clark Qian"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: superhero
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto

